---
services:
  s-ui-next:
    image: ghcr.io/felixbennettio/s-ui-next
    container_name: s-ui-next
    hostname: "s-ui-next"
    volumes:
      - "./db:/app/db"
      - "./cert:/app/cert"
    tty: true
    restart: unless-stopped
    ports:
      - "2095:2095"
      - "2096:2096"
    networks:
      - s-ui-next
    entrypoint: "./entrypoint.sh"

networks:
  s-ui-next:
    driver: bridge
